# Dockerfile

# NodeJS Version 18 Alpine
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json first
COPY package*.json ./

# Install Node packages
RUN npm install --legacy-peer-deps

# Copy the rest of the application files
COPY . .

# Set environment variables
ENV NODE_ENV=development

# Expose port 3000
EXPOSE 3000

# Command to run the application
CMD ["npm", "run", "dev"]


